// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__IQuickJS_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

// Internal function used for queueing buffers to native code
GMEXPORT double __EXT_NATIVE__IQuickJS_queue_buffer(char* __arg_buffer, double __arg_buffer_length);

GMEXPORT double __EXT_NATIVE__iqjs_init();
GMEXPORT double __EXT_NATIVE__iqjs_shutdown();
GMEXPORT double __EXT_NATIVE__iqjs_new_runtime(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_new_runtime_with_allocator(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_runtime(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_runtime_info(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_dump_flags(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_dump_flags(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_update_stack_top(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_run_gc(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_live_object(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_can_block(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_job_pending(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_pending_job_context(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_execute_pending_job(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__iqjs_get_version();
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_set_runtime_opaque(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_get_runtime_opaque(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_runtime_finalizer_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_remove_runtime_finalizer_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_mark_value_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_context(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_context_raw(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_dup_context(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_context(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_runtime(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_set_context_opaque(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_get_context_opaque(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_function_proto(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_base_objects(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_date(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_eval(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_regexp_compiler(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_regexp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_json(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_proxy(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_map_set(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_typed_arrays(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_promise(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_bigint(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_weak_ref(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_performance(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_dom_exception(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_intrinsic_atob(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_memory_limit(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_gc_threshold(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_gc_threshold(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_max_stack_size(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_compute_memory_usage(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__iqjs_dump_memory_usage(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_calloc_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_malloc_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_mallocz_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_realloc_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_free_rt(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_malloc_usable_size_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_calloc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_malloc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_mallocz(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_realloc(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_realloc2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_free(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_malloc_usable_size(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_strdup(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_strndup(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_atom_null(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_atom(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_atom_len(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_atom_uint32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_dup_atom(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_dup_atom_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_atom(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_atom_rt(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_atom_to_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_atom_to_string(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__iqjs_atom_to_cstring(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_value_to_atom(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_class_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_class_id(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_class_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_registered_class(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_class_name(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_class_proto(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_class_proto(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_class_exotic_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_null(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_undefined(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_true(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_false(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_exception(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_uninitialized(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_bool(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_int32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_int64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_uint32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_uint64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_float64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_number(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_bigint64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_biguint64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_catch_offset(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_string(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_string_len(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_string_utf16(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_atom_string(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_symbol(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_free_value_rt(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_dup_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_dup_value_rt(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_value_tag(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_nan(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_number(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_bigint(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_null(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_undefined(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_exception(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_uninitialized(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_string(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_symbol(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_object(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_module(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_error(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_uncatchable_error(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_uncatchable_error(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_clear_uncatchable_error(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_reset_uncatchable_error(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_exception(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_has_exception(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_internal_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_plain_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_range_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_reference_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_syntax_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_type_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_internal_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_plain_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_range_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_reference_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_syntax_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_type_error(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_dom_exception(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_throw_out_of_memory(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_equal(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_strict_equal(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_same_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_same_value_zero(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_bool(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_boolean(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_number(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_int32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_uint32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_int64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_index(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_float64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_bigint64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_biguint64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_int64_ext(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_string(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_property_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__iqjs_to_cstring(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_utf16(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object_proto(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object_class(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object_proto_class(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object_from(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_object_from_str(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_to_object_string(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_array(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_array_from(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_date(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_proxy(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_proxy_target(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_proxy_handler(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_function(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_async_function(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_constructor(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_constructor_bit(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_regexp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_map(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_set(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_weak_ref(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_weak_set(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_weak_map(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_data_view(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_array(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_proxy(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_date(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_property(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_property_uint32(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_property_int64(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_property_str(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_property_uint32(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_property_int64(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_property_str(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_has_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_extensible(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_prevent_extensions(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_delete_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_prototype(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_prototype(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_length(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_length(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_seal_object(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_freeze_object(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_own_property_names(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_own_property(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_define_property(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_define_property_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_define_property_value_uint32(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_define_property_value_str(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_define_property_get_set(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_constructor(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_instance_of(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_is_html_dda(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_set_opaque(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_get_opaque(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_get_opaque2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_get_any_opaque(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_detect_module(char* source);
GMEXPORT double __EXT_NATIVE__iqjs_eval(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_eval2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_eval_this(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_eval_this2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_eval_function(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_global_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_parse_json(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_json_stringify(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_array_buffer_copy(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_array_buffer_owned(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_detach_array_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_copy_array_buffer(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_array_buffer_copy(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_array_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_immutable_array_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_immutable_array_buffer(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_uint8_array_copy(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_typed_array(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_typed_array_buffer(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_uint8_array_copy(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_uint8_array_owned(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_typed_array_type(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_set_shared_array_buffer_policy(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_promise_capability(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_promise_state(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_promise_result(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_is_promise(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_settled_promise(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_create(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_add(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_remove(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_set_supported_attributes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_install(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_module_registry_free(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_import_meta(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_module_name(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_module_namespace(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_module_private_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_module_private_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_load_module(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_resolve_module(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_get_script_or_module_name(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_c_module_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_module_export(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_module_export(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_property_function_list_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_add_module_export_list_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_module_export_list_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_write_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_write_object2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_read_object(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unsafe_read_object2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_interrupt_handler_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_host_promise_rejection_tracker_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_set_promise_hook_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_remove_callback_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_gml_function_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_gml_function_data_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_new_gml_closure_adapter(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_register_gml_global_function(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_unregister_gml_global_function(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_enqueue_job_adapter(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_call(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_invoke(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_call_constructor(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__iqjs_call_constructor2(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);

